# Generated by Django 5.2.7 on 2025-12-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='¿Destacado en Home?'),
        ),
    ]
