# Generated by Django 5.2.7 on 2025-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración'),
        ),
    ]
